
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>IMEXSOL | Imports Exports Software Solutions</title>
  <link rel="icon" href="img/favicon.ico">
  <!--[if IE 8]><html class="ie8"><![endif]-->
  <!-- Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <!-- Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,700,800,300' rel='stylesheet' type='text/css'>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Theme -->
  <link rel="stylesheet" type="text/css" href="css/theme.css" id="color-style">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <div class="wrapper-body">

  
    <!--SECTION HEADING-->
    <!--===============================================================-->
    <div class="section-heading-page">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <h1 class="heading-page text-center-xs">US Exports Declarations (AES)</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb text-right text-center-xs">
              <li>
                <a href="#">Home</a>
              </li>
              <li>
                <a href="#">Solutions</a>
              </li>
              <li class="active">US Exports Declarations (AES)</li>
            </ol>
          </div>
        </div>
      </div>
    </div>

<div class="container">
<div class="row"> 
<div class="col-sm-12">

       <h1>We generate for you the best export compliance tool.
       <br>
       <small>Goods exported from United States in many cases require to be reported to the Automated Export System(AES) in the form of the Electronic Export Information(EEI) that only can be filled electronically. We implement in our system The Best Practices Program, developed by The U.S. Census Bureau to help to Export Community.</small>   
       <br>
       <small>Our Export Module help you to obtain your ITN. Before a ITN request is sent we verify that all the information required for your shipments, to avoid delays in your declarations.</small> </h1>

</div>
</div>
</div>

<div class="container">
<div class="row"> 
<div class="col-sm-12">

            <img class="img-responsive center-block" src="img/AESMenu.png" alt="theme-img">
            

</div>
</div>
</div>

<div class="container">
<div class="row"> 
<div class="col-sm-12">

       <h1>"Take control of your EEIs in one single screen. Transmit, print, export and send by e-mail all from the ribbon bar included on this module."</h1>

</div>
</div>
</div>

<div class="container">
<div class="row"> 
<div class="col-sm-12">
<div class="text-center-xs">
       <h2>"Benefits"
       <br>
              <small>
         Integration – We can integrate with your actual systems directly to your database, via Web Services or trough EDI files to automate the input process.
       </small>
       <br>
       <small>
         Input Profiles – EEI Profiles can be generated by Customer and includes USPPI, Consignee, MOT, Carrier, Destination and Goods information for reduce input time.
       </small>
       <small>
         Validation and Instant Feedback – Our direct connection to CBP generate your ITN on real time, avoiding the waiting time on other systems.
       </small></h2>

       </div>
</div>
</div>
</div>

    <!--SECTION -->
    <!--===============================================================-->
    <div class="section section-sm section-bottom section-pricetable-v1">
      <div class="container">
        <div class="row text-center">
          <div class="col-sm-12">
            <h3 class="title-lg title-section hr">HERE OUR PRICES</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-3">
            <div class="pricetable pricetable-v1">
              <h3 class="membership">Monthly Volume</h3>
<h3 class="price">Initial</h3>
              <ul class="ul-pricetable list-unstyled">
                <li><i class="fa fa-envelope"></i> > 400 </li>
                 <li><i class="fa fa-envelope"></i>401 - 800 </li>
                <li><i class="fa fa-envelope"></i> < 800</li>

              </ul>
              
            </div>
          </div>
          <div class="col-sm-4">
            <div class="pricetable pricetable-v1">
              <h3 class="membership">EII Price</h3>
<h3 class="price">Registration</h3>
              <ul class="ul-pricetable list-unstyled">
                <li><i class="fa fa-cloud-download"></i>$ 0.40 usd</li>
                <li><i class="fa fa-cogs"></i>$ 0.35 usd </li>
                <li><i class="fa fa-envelope"></i>$0.30</li>

              </ul>
              
            </div>
          </div>
          <div class="col-sm-5">
            <div class="pricetable pricetable-v1">
              <h3 class="membership">Description</h3>
<h3 class="price">Fee - $500 usd</h3>
              <ul class="ul-pricetable list-unstyled">
                <li><i class="fa fa-cloud-download"></i>Less than 400 Monthly EEI.</li>
                <li><i class="fa fa-cogs"></i>Price for this transaction range is 35 cents.</li>
                <li><i class="fa fa-envelope"></i>After more than 800 shipment price is 30¢.</li>

              </ul>
              
            </div>
          </div>
        </div>
      </div>
    </div>
   

    <!--SECTION FOOTER BOTTOM -->
    <!--===============================================================-->
 
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="js/bootstrap.min.js"></script>
  <script src="js/theme.js"></script>
  <script src="js/style-switcher.js"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59515546-1', 'auto');
    ga('send', 'pageview');

  </script>
<script type="text/javascript">
/* <![CDATA[ */
(function(){try{var s,a,i,j,r,c,l=document.getElementsByTagName("a"),t=document.createElement("textarea");for(i=0;l.length-i;i++){try{a=l[i].getAttribute("href");if(a&&a.indexOf("/cdn-cgi/l/email-protection") > -1  && (a.length > 28)){s='';j=27+ 1 + a.indexOf("/cdn-cgi/l/email-protection");if (a.length > j) {r=parseInt(a.substr(j,2),16);for(j+=2;a.length>j&&a.substr(j,1)!='X';j+=2){c=parseInt(a.substr(j,2),16)^r;s+=String.fromCharCode(c);}j+=1;s+=a.substr(j,a.length-j);}t.innerHTML=s.replace(/</g,"&lt;").replace(/>/g,"&gt;");l[i].setAttribute("href","mailto:"+t.value);}}catch(e){}}}catch(e){}})();
/* ]]> */
</script>
</body>

</html>
